### ISSUE TITLE
modal is not a function

### ISSUE THREAD

**Issue by ChenZhaobin** [derlin/semantic-modals#1]
Very thanks for your code.
when I run the basic example ,some thing is wrong with the exception below:
angular.js:11383 TypeError: $(...).modal is not a function at

   $( modalElement )  //
                        .modal( 'setting', 'closable', options.cancelable === false ? false : true )  //
                        .modal( 'show' );

**Comment by derlin** [comment]
Thank you for your interest. How exactly did you run the examples? Are you using any framework?

**Comment by derlin** [comment]
Thank you for your interest. The modal function is normally part of the semantic-ui framework: http://semantic-ui.com/modules/modal.html. Did you include it in your test ? Further examples here: http://derlin.github.io/semantic-modals/

**Comment by derlin** [comment]
closing the issue since I got no further information. Guess it was a missing dep.
